### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Mgamerz** [bgbennyboy/Psychonauts-Explorer#3]
What's the license on this? I have ported some of the ISB code to C#, but I am not sure what the license for this is. The program I want to put it into is GPLv3.

**Comment by bgbennyboy** [comment]
Its MPL 2.0 which I think is compatible with GPL. If not I can always dual licence.
Out of curiosity what part did you port? I dont remember ISB files being used in any other games.

**Comment by Mgamerz** [comment]
I ported the audio dumper code (and Xbox ADPCM converter) to
https://github.com/Mgamerz/ME3Explorer. Mass Effect (1) also uses
ISB/ISACT, we have always recommended your software for users who want to
get at the audio, but I wanted to use the code to work with some audio that
is embedded in unreal exports. I am having issues with it though, the data
looks like ISB but it seems slightly different in the data sections (not
pcm or ogg nor Xbox adpcm). The header is also icbftitl and not isbftitl.

If you're interested in seeing the data/issues, I could use some help
trying to decode some of this data in SoundNodeWave (the embedded sound).
It looks very similar to ISB file format, but I can't get it to work. I
can't find any documentation at all on ISACT.

Thanks,
Mgamerz

**Comment by bgbennyboy** [comment]
How strange, I always assumed that .isb was a custom container format that Doublefine made. Doing research now it looks like it was audio middleware by Creative Labs.

Looking back at Psychonauts (its been 15 years since I wrote most of Psychonauts Explorer) the  .isb files have a corresponding .icb file for most but not all of the files. In the icb files they have 'icbfstat' strings after the RIFF header. The data in the icb files looks like extra stuff about each track, loop points etc. There are no data blocks in the icb files in Psychonauts. Basically the whole isb/icb split looks a bit like what Microsoft did with XACT and wavebanks/soundbanks.

With that file data I would guess that its using a different codec and the first things I would try are XMA, and xWMA. It could also be IMA ADPCM since that is (apparently) very similar to xbox adpcm.

[Here ](https://www.mixonline.com/sfp/audio-middleware-369339)talks about ISACT
"The program supports WAV, AIFF, CDDA (import), PCM, ADPCM, WMA, XMA and Ogg Vorbis (export) sound formats" so with Mass Effect 1 being an Xbox 360 game I would guess at XMA.

**Comment by Mgamerz** [comment]
I am working on the PC port of ME1 - Given how sloppy it seems to be I
almost wonder if they just shipped Xbox embedded audio and called it a day.

I will see if I can find other formats. I am not too skilled at audio stuff.
